version: "3"
services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  monitoring:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - sqlite3
